<#
.SYNOPSIS
    Generate INDEX.md for docs/ and marketing/ of a product.

.DESCRIPTION
    Scans frontmatter of all .md, groups by type, emits a manifest table.
    - approved and review -> main list
    - draft -> "Drafts" section
    - deprecated -> skipped

.PARAMETER Product
    Product slug.

.PARAMETER Root
    Root dir. Default: C:\src\products.

.PARAMETER Target
    docs | marketing | all.

.EXAMPLE
    .\gen-index.ps1 -Product shop
    .\gen-index.ps1 -Product cafe -Target docs
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Product,
    [string]$Root = "C:\src\products",
    [ValidateSet('docs','marketing','all')][string]$Target = 'all'
)

$ErrorActionPreference = 'Stop'

$productDir = Join-Path $Root $Product
if (-not (Test-Path -Path $productDir -PathType Container)) {
    Write-Error "Product '$Product' not found in $Root"
    exit 1
}

$excludePattern = 'node_modules|\.git|bin|obj|dist|build|__pycache__|\.next'

function Get-Frontmatter {
    param([string]$Path)
    $content = Get-Content -Path $Path -Raw -Encoding UTF8
    if ($content -match '(?s)^---\r?\n(.*?)\r?\n---') {
        return $Matches[1]
    }
    return $null
}

function Parse-Frontmatter {
    param([string]$Yaml)
    $result = [ordered]@{}
    if (-not $Yaml) { return $result }
    foreach ($line in $Yaml -split "`r?`n") {
        if ($line -match '^\s*#') { continue }
        if ($line -match '^\s*$') { continue }
        if ($line -match '^(\w+):\s*(.*)$') {
            $key = $Matches[1]
            $value = $Matches[2].Trim()
            if ($value -match '^["''](.*)["'']$') { $value = $Matches[1] }
            if ($value -match '^\[(.*)\]$') {
                $inner = $Matches[1]
                $list = @()
                if ($inner.Trim() -ne '') {
                    foreach ($item in $inner -split ',') {
                        $list += $item.Trim().Trim('"').Trim("'")
                    }
                }
                $result[$key] = $list
            } else {
                $result[$key] = $value
            }
        }
    }
    return $result
}

function New-IndexFile {
    param(
        [string]$ScanRoot,
        [string]$OutputFile,
        [string]$ProductName,
        [string]$SectionTitle
    )

    if (-not (Test-Path -Path $ScanRoot -PathType Container)) {
        Write-Warning "Folder $ScanRoot does not exist, skipping"
        return
    }

    $files = Get-ChildItem -Path $ScanRoot -Recurse -File -Filter "*.md" |
        Where-Object { $_.FullName -notmatch $excludePattern } |
        Where-Object { $_.Name -ne 'INDEX.md' -and $_.Name -ne 'README.md' }

    $groups = @{}
    $drafts = @()

    foreach ($file in $files) {
        $yaml = Get-Frontmatter -Path $file.FullName
        if (-not $yaml) { continue }
        $fm = Parse-Frontmatter -Yaml $yaml

        $type = $fm['type']
        $status = $fm['status']
        $title = $fm['title']
        $owner = $fm['owner']
        $reviewed = $fm['last_reviewed']
        $locale = $fm['locale']

        if (-not $type -or -not $title) { continue }
        if ($status -eq 'deprecated') { continue }

        $rel = $file.FullName.Substring($ScanRoot.Length).TrimStart('\','/').Replace('\','/')

        $entry = [PSCustomObject]@{
            Title    = $title
            Path     = $rel
            Owner    = $owner
            Reviewed = $reviewed
            Locale   = $locale
            Status   = $status
            Type     = $type
        }

        if ($status -eq 'draft') {
            $drafts += $entry
            continue
        }

        $groupKey = $type
        if ($type -eq 'manual' -or $type -eq 'help') {
            $groupKey = "$type ($locale)"
        }

        if (-not $groups.ContainsKey($groupKey)) { $groups[$groupKey] = @() }
        $groups[$groupKey] += $entry
    }

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine("# $ProductName : $SectionTitle index")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("> Generated by tools/gen-index.ps1 -- $(Get-Date -Format 'yyyy-MM-dd HH:mm')")
    [void]$sb.AppendLine("")

    $order = @('manual (ru)','manual (en)','help (ru)','help (en)',
               'tech','arch','adr','api','runbook','release',
               'roadmap','design','positioning','pitch','showcase',
               'hero','campaign','brand','mockup','standard','readme')

    $orderedKeys = @()
    foreach ($k in $order) {
        if ($groups.ContainsKey($k)) { $orderedKeys += $k }
    }
    foreach ($k in $groups.Keys) {
        if ($orderedKeys -notcontains $k) { $orderedKeys += $k }
    }

    [void]$sb.AppendLine("## By type")
    [void]$sb.AppendLine("")
    foreach ($k in $orderedKeys) {
        $label = $k.Substring(0,1).ToUpper() + $k.Substring(1)
        [void]$sb.AppendLine("### $label")
        foreach ($e in ($groups[$k] | Sort-Object Title)) {
            $line = "- [$($e.Title)]($($e.Path))"
            $meta = @()
            if ($e.Owner) { $meta += "owner: $($e.Owner)" }
            if ($e.Reviewed) { $meta += "reviewed: $($e.Reviewed)" }
            if ($meta.Count -gt 0) {
                $line += " -- " + ($meta -join ' | ')
            }
            [void]$sb.AppendLine($line)
        }
        [void]$sb.AppendLine("")
    }

    if ($drafts.Count -gt 0) {
        [void]$sb.AppendLine("## Drafts")
        [void]$sb.AppendLine("")
        foreach ($e in ($drafts | Sort-Object Title)) {
            [void]$sb.AppendLine("- [$($e.Title)]($($e.Path)) -- owner: $($e.Owner) | draft")
        }
        [void]$sb.AppendLine("")
    }

    Set-Content -Path $OutputFile -Value $sb.ToString() -Encoding UTF8 -NoNewline
    Write-Host "Generated: $OutputFile"
}

if ($Target -in @('docs','all')) {
    New-IndexFile -ScanRoot (Join-Path $productDir "docs") `
                  -OutputFile (Join-Path $productDir "docs\INDEX.md") `
                  -ProductName $Product `
                  -SectionTitle "Documentation"
}

if ($Target -in @('marketing','all')) {
    New-IndexFile -ScanRoot (Join-Path $productDir "marketing") `
                  -OutputFile (Join-Path $productDir "marketing\INDEX.md") `
                  -ProductName $Product `
                  -SectionTitle "Marketing"
}

Write-Host ""
Write-Host "Done." -ForegroundColor Green
